import type { WindyParameter } from "./parameterIds.js";

/** Forecast model identifiers accepted by the Windy Point Forecast API. */
export const WINDY_MODELS = [
  // Weather models
  "gfs",
  "icon",
  "iconD2",
  "iconEu",
  "arome",
  "aromeAntilles",
  "aromeFrance",
  "aromeReunion",
  "namConus",
  "namHawaii",
  "namAlaska",
  "hrrrConus",
  "hrrrAlaska",
  "canHrdps",
  // Sea models
  "gfsWave",
  "iconWave",
  "iconEuWave",
  "canRdwpsWave",
  "cmems",
  // Air quality models
  "cams",
  "camsEu",
] as const;

export type WindyModel = (typeof WINDY_MODELS)[number];

export type ModelCategory = "weather" | "sea" | "air_quality";

export interface ModelInfo {
  id: WindyModel;
  category: ModelCategory;
  /** Geographic coverage and resolution notes. */
  coverage: string;
  /** When to pick this model for outdoor/trail planning. */
  useWhen: string;
  /** Parameters supported by this model (from Windy docs compatibility matrix). */
  parameters: readonly WindyParameter[];
}

export const MODEL_INFO: Record<WindyModel, ModelInfo> = {
  gfs: {
    id: "gfs",
    category: "weather",
    coverage: "Global (NOAA GFS, ~13 km). Default worldwide fallback.",
    useWhen:
      "Any location globally when no regional high-res model applies. Good baseline " +
      "for multi-day trail planning.",
    parameters: [
      "temp",
      "dewpoint",
      "precip",
      "convPrecip",
      "snowPrecip",
      "wind",
      "windGust",
      "cape",
      "ptype",
      "lclouds",
      "mclouds",
      "hclouds",
      "rh",
      "gh",
      "pressure",
    ],
  },
  icon: {
    id: "icon",
    category: "weather",
    coverage: "Global (DWD ICON-Global).",
    useWhen: "Global coverage with a European model; alternative to GFS worldwide.",
    parameters: [
      "temp",
      "dewpoint",
      "precip",
      "convPrecip",
      "snowPrecip",
      "wind",
      "windGust",
      "cape",
      "ptype",
      "lclouds",
      "mclouds",
      "hclouds",
      "rh",
      "gh",
      "pressure",
    ],
  },
  iconD2: {
    id: "iconD2",
    category: "weather",
    coverage: "Germany, Austria, Switzerland — high resolution (~2 km).",
    useWhen: "Alpine trails in DE/AT/CH where terrain detail matters.",
    parameters: [
      "temp",
      "dewpoint",
      "precip",
      "convPrecip",
      "snowPrecip",
      "wind",
      "windGust",
      "cape",
      "ptype",
      "lclouds",
      "mclouds",
      "hclouds",
      "rh",
      "gh",
      "pressure",
    ],
  },
  iconEu: {
    id: "iconEu",
    category: "weather",
    coverage: "Europe and surrounding areas (~7 km).",
    useWhen: "European hiking/cycling; better than GFS for the Alps, Pyrenees, etc.",
    parameters: [
      "temp",
      "dewpoint",
      "precip",
      "convPrecip",
      "snowPrecip",
      "wind",
      "windGust",
      "cape",
      "ptype",
      "lclouds",
      "mclouds",
      "hclouds",
      "rh",
      "gh",
      "pressure",
    ],
  },
  arome: {
    id: "arome",
    category: "weather",
    coverage: "France and surrounding areas (Météo-France AROME).",
    useWhen: "French trails including Alps, Massif Central, Pyrenees fringes.",
    parameters: [
      "temp",
      "dewpoint",
      "precip",
      "convPrecip",
      "snowPrecip",
      "wind",
      "windGust",
      "cape",
      "ptype",
      "lclouds",
      "mclouds",
      "hclouds",
      "rh",
      "gh",
      "pressure",
      "cbase",
      "visibility",
      "weatherWarnings",
    ],
  },
  aromeAntilles: {
    id: "aromeAntilles",
    category: "weather",
    coverage: "French Antilles (Caribbean).",
    useWhen: "Guadeloupe, Martinique, and nearby islands.",
    parameters: [
      "temp",
      "dewpoint",
      "precip",
      "convPrecip",
      "snowPrecip",
      "wind",
      "windGust",
      "cape",
      "ptype",
      "lclouds",
      "mclouds",
      "hclouds",
      "rh",
      "gh",
      "pressure",
      "weatherWarnings",
    ],
  },
  aromeFrance: {
    id: "aromeFrance",
    category: "weather",
    coverage: "Metropolitan France only.",
    useWhen: "Mainland France trails when you want the France-specific AROME run.",
    parameters: [
      "temp",
      "dewpoint",
      "precip",
      "convPrecip",
      "snowPrecip",
      "wind",
      "windGust",
      "cape",
      "ptype",
      "lclouds",
      "mclouds",
      "hclouds",
      "rh",
      "gh",
      "pressure",
      "cbase",
      "visibility",
      "weatherWarnings",
    ],
  },
  aromeReunion: {
    id: "aromeReunion",
    category: "weather",
    coverage: "Réunion island (Indian Ocean).",
    useWhen: "Piton des Neiges, cirques, and Réunion hiking.",
    parameters: [
      "temp",
      "dewpoint",
      "precip",
      "convPrecip",
      "snowPrecip",
      "wind",
      "windGust",
      "cape",
      "ptype",
      "lclouds",
      "mclouds",
      "hclouds",
      "rh",
      "gh",
      "pressure",
      "weatherWarnings",
    ],
  },
  namConus: {
    id: "namConus",
    category: "weather",
    coverage: "Continental USA and surrounding areas (NAM).",
    useWhen: "US lower-48 trail forecasts (Appalachian, Rockies, etc.).",
    parameters: [
      "temp",
      "dewpoint",
      "precip",
      "convPrecip",
      "snowPrecip",
      "wind",
      "windGust",
      "cape",
      "ptype",
      "lclouds",
      "mclouds",
      "hclouds",
      "rh",
      "pressure",
    ],
  },
  namHawaii: {
    id: "namHawaii",
    category: "weather",
    coverage: "Hawaii.",
    useWhen: "Hawaiian island trails and volcanoes.",
    parameters: [
      "temp",
      "dewpoint",
      "precip",
      "convPrecip",
      "snowPrecip",
      "wind",
      "windGust",
      "cape",
      "ptype",
      "lclouds",
      "mclouds",
      "hclouds",
      "rh",
      "pressure",
    ],
  },
  namAlaska: {
    id: "namAlaska",
    category: "weather",
    coverage: "Alaska and surrounding areas.",
    useWhen: "Alaskan wilderness and mountain routes.",
    parameters: [
      "temp",
      "dewpoint",
      "precip",
      "convPrecip",
      "snowPrecip",
      "wind",
      "windGust",
      "cape",
      "ptype",
      "lclouds",
      "mclouds",
      "hclouds",
      "rh",
      "pressure",
    ],
  },
  hrrrConus: {
    id: "hrrrConus",
    category: "weather",
    coverage: "Continental USA — high resolution (~3 km, short-range).",
    useWhen: "Same-day / next-day US trail weather where convection and terrain matter.",
    parameters: [
      "temp",
      "dewpoint",
      "precip",
      "convPrecip",
      "snowPrecip",
      "wind",
      "windGust",
      "cape",
      "ptype",
      "lclouds",
      "mclouds",
      "hclouds",
      "rh",
      "pressure",
    ],
  },
  hrrrAlaska: {
    id: "hrrrAlaska",
    category: "weather",
    coverage: "Alaska — high resolution short-range.",
    useWhen: "Detailed short-range forecasts for Alaskan trails.",
    parameters: [
      "temp",
      "dewpoint",
      "precip",
      "convPrecip",
      "snowPrecip",
      "wind",
      "windGust",
      "cape",
      "ptype",
      "lclouds",
      "mclouds",
      "hclouds",
      "rh",
      "pressure",
    ],
  },
  canHrdps: {
    id: "canHrdps",
    category: "weather",
    coverage: "Canada — high resolution (HRDPS).",
    useWhen: "Canadian Rockies, Coast Mountains, and other CA trail areas.",
    parameters: [
      "temp",
      "dewpoint",
      "precip",
      "snowPrecip",
      "wind",
      "windGust",
      "cape",
      "lclouds",
      "mclouds",
      "hclouds",
      "rh",
      "pressure",
    ],
  },
  gfsWave: {
    id: "gfsWave",
    category: "sea",
    coverage:
      "Global ocean waves (excludes Hudson Bay partly, Black Sea, Caspian, most Arctic).",
    useWhen: "Coastal hikes, beach trails, kayak/ferry crossings on open ocean.",
    parameters: ["waves", "wavesPower", "windWaves", "swell1", "swell2"],
  },
  iconWave: {
    id: "iconWave",
    category: "sea",
    coverage: "Global wave model (DWD ICON-GWAM).",
    useWhen: "Global marine conditions; alternative wave model to gfsWave.",
    parameters: ["waves", "wavesPower", "swell1", "swell2"],
  },
  iconEuWave: {
    id: "iconEuWave",
    category: "sea",
    coverage: "European seas (ICON-EWAM).",
    useWhen: "Mediterranean, Atlantic fringe, North Sea coastal trails.",
    parameters: ["waves", "wavesPower", "swell1", "swell2"],
  },
  canRdwpsWave: {
    id: "canRdwpsWave",
    category: "sea",
    coverage: "Canadian waters.",
    useWhen: "Pacific/Atlantic/Arctic coastal routes in Canada.",
    parameters: ["waves", "wavesPower", "swell1", "swell2"],
  },
  cmems: {
    id: "cmems",
    category: "sea",
    coverage: "Global ocean currents (Copernicus Marine Service).",
    useWhen: "Coastal current safety for swimming, paddling, or tidal flat crossings.",
    parameters: ["currents", "currentsTide"],
  },
  cams: {
    id: "cams",
    category: "air_quality",
    coverage: "Global air quality (Copernicus CAMS).",
    useWhen: "Smoke, dust, or pollution affecting trail air quality worldwide.",
    parameters: [
      "aqi",
      "so2sm",
      "dustsm",
      "cosc",
      "go3",
      "no2",
      "pm10",
      "pm2p5",
    ],
  },
  camsEu: {
    id: "camsEu",
    category: "air_quality",
    coverage: "Europe — includes pollen (CAMS regional).",
    useWhen: "European trails during hay-fever season or smog events.",
    parameters: [
      "aqi",
      "so2sm",
      "dustsm",
      "cosc",
      "go3",
      "no2",
      "pm10",
      "pm2p5",
      "pollenAlder",
      "pollenBirch",
      "pollenGrass",
      "pollenMugwort",
      "pollenOlive",
      "pollenRagweed",
    ],
  },
};

/** Default model when the caller does not specify one. */
export const DEFAULT_WEATHER_MODEL: WindyModel = "gfs";

/** Return parameters from the request that the given model does not support. */
export function unsupportedParameters(
  model: WindyModel,
  parameters: WindyParameter[],
): WindyParameter[] {
  const supported = new Set(MODEL_INFO[model].parameters);
  return parameters.filter((p) => !supported.has(p));
}
